- hosts: localhost
  become: true
  vars:
    myusername: haplo
    myhome: /home/haplo
    # defaults file for terraform-role
    terraform_version: 0.12.20
    terraform_dir: /opt/terraform
    terraform_user: terraform
    terraform_master: blah
  tasks:
    # Update entire system
    - include: tasks/system/nfs-client.yml

