- hosts: localhost
  become: true
  vars:
    myusername: haplo
    myhome: /home/haplo
    # defaults file for terraform-role
    terraform_version: 0.12.20
    terraform_dir: /opt/terraform
    terraform_user: terraform
  pre_tasks:
    - name: Update Repositories
      apt: update_cache=yes
      changed_when: false
  tasks:
    # Update entire system
    - include: tasks/software/update-system.yml
    #- name: Adding Ansible Settings
    # Ansible Settings
    - include: tasks/ansible/sudoers.yml

    # Software Settings
    - include: tasks/software/repos.yml
    - include: tasks/software/docker.yml
    - include: tasks/software/apt.yml
    - include: tasks/software/snap.yml
    - include: tasks/software/pip.yml
    - include: tasks/software/tfenv-tgenv.yml
    # - include: tasks/software/terraform.yml

    # System Settings
    - include: tasks/system/sysctl.yml
    - include: tasks/system/nsswitch.yml
    - include: tasks/system/services.yml
    - include: tasks/system/timezone.yml
    - include: tasks/system/ufw.yml
    - include: tasks/system/cpu.yml
    - include: tasks/system/screenshot.yml
      #- include: tasks/system/dns.yml
    # User Settings
    - include: tasks/user/groups.yml
    - include: tasks/user/users.yml
    - include: tasks/user/folders.yml
    - include: tasks/user/dotfiles.yml
    - include: tasks/user/git-config.yml
    - include: tasks/user/cron.yml
    - include: tasks/user/shell.yml
    - include: tasks/user/shortcuts.yml
    - include: tasks/user/general-user-settings.yml

    # - include: tasks/user/scripts.yml
    - include: tasks/user/permissions.yml

    # User Visual Settings
    # Running defaults for now
    - include: tasks/user/visual/theme.yml
    # - include: tasks/user/visual/wallpaper.yml
    - include: tasks/user/visual/desktop-icons.yml

    # System cleanup
    - include: tasks/software/update-system.yml
