- hosts: localhost
  become: true
  vars:
    myusername: dustin
    myhome: /home/dustin
  pre_tasks:
    - name: Update Repositories
      apt: update_cache=yes
      changed_when: false
  tasks:
    - include: tasks/user/users.yml
    - include: tasks/user/shell.yml
