- name: Create a directory if it does not exist
  file:
    path: "{{ item }}"
    owner: "{{ myusername }}"
    group: "{{ myusername }}"
    state: directory
    mode: '0755'
  with_items:
    - "/home/{{ myusername }}/ubuntu/scratch"
    - "/home/{{ myusername }}/tmp"
    - "/home/{{ myusername }}/sync/gdrive-br"
    - "/home/{{ myusername }}/private"
    - "/home/{{ myusername }}/Downloads/software"
    - "/home/{{ myusername }}/.config/ncspot"
    - "/home/{{ myusername }}/.config/kitty"
    - "/home/{{ myusername }}/.config/nvim"
    - "/home/{{ myusername }}/.local/bin"
    - "/home/{{ myusername }}/bin"
