---
- name: Download debian package for Discord if on Ubuntu
  get_url:
    url: https://discordapp.com/api/download?platform=linux&format=deb
    dest: /tmp/discord.deb
  when: "'64' in ansible_architecture and 'Ubuntu' == ansible_distribution"

- name: Install Discord latest deb
  apt:
    deb: /tmp/discord.deb
...
