---
- name: Download debian package for Discord if on Ubuntu
  get_url:
    url: https://discordapp.com/api/download?platform=linux&format=deb
    dest: /home/{{ myusername }}/Downloads/software/discord.deb
  when: "'64' in ansible_architecture and 'Ubuntu' == ansible_distribution"
  register: discord_installer

- name: Install Discord latest deb
  apt:
    deb: {{ discord_installer.dest }}
...
